/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'andrew' at '5/11/16 8:32 AM' with Gradle 2.13
 *
 * @author andrew, @date 5/11/16 8:32 AM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
